### ISSUE TITLE
Annotations while porting overlay-sr for NetTopologySuite

### ISSUE THREAD

**Issue by FObermaier** [dr-jts/jts#4]
While porting the overlay-sr branch to NetTopologySuite I came across some _issues_ which I'm going to report here:
* [InherentScaleFilter ](https://github.com/dr-jts/jts/blob/4d9fdbed8f7d6bb6b508967dcf7061be9ae6460d/modules/core/src/main/java/org/locationtech/jts/operation/overlayng/PrecisionUtil.java#L334) will benefit from a filter that works on the entire coordinate sequence (https://github.com/locationtech/jts/issues/505).
* [OverlayEdge](https://github.com/dr-jts/jts/blob/4d9fdbed8f7d6bb6b508967dcf7061be9ae6460d/modules/core/src/main/java/org/locationtech/jts/operation/overlayng/OverlayEdge.java#L203-L219) `nextResult()` and `setResultNext(...)` should be aligned, same for `nextResultMax()` and `setResultNextMax(...)`.

**Comment by dr-jts** [comment]
Thanks for the comments.

* `InherentScaleFilter`is so slow as to be essentially useless.  I no longer recommend using it. So yes this would be a good enhancement at some point, but not essential for this codebase
* Are you suggesting using e.g. `nextResult` and `setNextResult` ?  There is some logic to that.  My original thinking was that it's nicer to have the `setResultXXX` methods sort beside one another alphabetically.

**Comment by dr-jts** [comment]
And I'm keen to hear how OverlayNG works in NTS! Be sure and try out the recent addition of `SnappingNoder` - it seems to solve all robustness problems with no impact on performance.

**Comment by FObermaier** [comment]
> Are you suggesting using e.g. `nextResult` and `setNextResult` ?

Yes, when porting I was wondering whether those refer to the same thing. In C# we use properties for these _simple_ functions, which makes using different names awkward.

> And I'm keen to hear how OverlayNG works in NTS!

This is currently work in progress:
https://github.com/NetTopologySuite/NetTopologySuite/pull/412

**Comment by dr-jts** [comment]
> > Are you suggesting using e.g. `nextResult` and `setNextResult` ?
> 
> Yes, when porting I was wondering whether those refer to the same thing. In C# we use properties for these _simple_ functions, which makes using different names awkward.

I'll change the setter names.
> 
> This is currently work in progress:
> [NetTopologySuite/NetTopologySuite#412](https://github.com/NetTopologySuite/NetTopologySuite/pull/412)

Thanks.  Just be aware that the code hasn't been officially released yet, so there may well be more renaming and refactoring.

**Comment by dr-jts** [comment]
Setter names changed: https://github.com/dr-jts/jts/commit/fc6c47d1d0d23496826d8777e036a585587eee3d
